// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"uuid"

	"github.com/jackc/pgx/v5/pgtype"
)

type Restaurant struct {
	ID         uuid.UUID
	FsqID      string
	Name       string
	Category   string
	Address    string
	Area       string
	Answers    []byte
	PriceLevel pgtype.Int4
	Lat        float64
	Lon        float64
	CreatedAt  pgtype.Timestamptz
	ModifiedAt pgtype.Timestamptz
}
