// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restaurants.sql

package database

import (
	"context"
	"uuid"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRestaurants = `-- name: ListRestaurants :many
SELECT id, name, category, address, area, answers, price_level, lat, lon
FROM restaurants
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListRestaurantsParams struct {
	Cursor   uuid.UUID
	RowLimit int32
}

type ListRestaurantsRow struct {
	ID         uuid.UUID
	Name       string
	Category   string
	Address    string
	Area       string
	Answers    []byte
	PriceLevel pgtype.Int4
	Lat        float64
	Lon        float64
}

func (q *Queries) ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]ListRestaurantsRow, error) {
	rows, err := q.db.Query(ctx, listRestaurants, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRestaurantsRow
	for rows.Next() {
		var i ListRestaurantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.Area,
			&i.Answers,
			&i.PriceLevel,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
